import { Footer } from '@/app/_components/Footer';
import { Header } from '@/app/_components/Header';
import {
  ColorModeScript,
  Container,
  ThemeSchemeScript,
  UIProvider,
} from '@/components/ui';
import type { Metadata } from 'next';
import { theme } from '../../theme';
import { config } from '../../theme/config';
// import './globals.css';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ColorModeScript defaultValue={config.defaultColorMode} />
        <ThemeSchemeScript defaultValue={config.defaultThemeScheme} />
        <UIProvider theme={theme} config={config}>
          <Container.Root minH="100dvh">
            <Header />
            <Container.Body as="main" gap={{ base: 'lg', md: 'sm' }}>
              {children}
            </Container.Body>
            <Footer />
          </Container.Root>
        </UIProvider>
      </body>
    </html>
  );
}
